name: "Continuous Integration"

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:
  phpunit:
    name: PHP ${{ matrix.php-version }} (${{ matrix.dependency-version }})

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
        dependency-version: [prefer-lowest, prefer-stable]
        experimental: [false]

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@2.25.4
      with:
        php-version: ${{ matrix.php-version }}
        tools: composer:v2
        coverage: pcov

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer packages
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Install dependencies (PHP 8)
      if: steps.composer-cache.outputs.cache-hit != 'true' && matrix.php-version >= 8
      run: composer update --${{ matrix.dependency-version }} --ignore-platform-req=php --no-progress --no-interaction

    - name: Run test suite
      run: composer run-script test-ci
